matrix:
  include:
    - os: linux
      language: node_js
      node_js: "12"
      sudo: required
      dist: xenial

script:
  - npm run dev &
  - npm run jest
after_success:
  - npm run coveralls
branches:
  - release
  - test